## Numpy: Package for Multidinensional array

In [1]:
import numpy as np

In [4]:
simple_list=[6,7,8]
np.array(simple_list)

array([6, 7, 8])

In [5]:
arr=np.array([6,7,9])
arr

array([6, 7, 9])

In [6]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(1,85,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones(20,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
np.ones((3,6),int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [16]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [17]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [25]:
np.eye(10, dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [26]:
np.random.rand(2,4)

array([[0.98752682, 0.3500337 , 0.37053695, 0.74937837],
       [0.80707049, 0.41224929, 0.4805697 , 0.48964047]])

In [27]:
arr=np.random.rand(2,4)
arr

array([[0.33827057, 0.47500957, 0.77496859, 0.52962185],
       [0.36768737, 0.30377927, 0.21248742, 0.32878078]])

In [29]:
np.random.randn(2,4)

array([[ 1.10744172, -1.43862069,  0.83481194,  1.83787331],
       [ 0.56528767, -0.30361247,  1.34721831, -0.19893164]])

In [30]:
np.random.randint(20,56,100)

array([44, 35, 53, 25, 35, 36, 39, 44, 53, 25, 42, 48, 39, 27, 27, 26, 51,
       33, 53, 23, 27, 20, 54, 38, 23, 35, 28, 37, 24, 30, 37, 55, 23, 39,
       43, 52, 46, 26, 20, 28, 31, 25, 28, 22, 49, 42, 50, 49, 45, 48, 41,
       20, 49, 50, 51, 30, 40, 42, 47, 49, 28, 33, 41, 28, 28, 51, 43, 45,
       49, 52, 44, 20, 31, 28, 20, 42, 30, 27, 30, 48, 23, 48, 24, 28, 22,
       20, 36, 36, 24, 25, 36, 28, 32, 20, 34, 30, 21, 43, 30, 45])

In [31]:
sample_array=np.arange(30)

In [32]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [38]:
a=np.random.randint(0,100,20)
a

array([35, 41, 52, 36, 29, 79, 74, 90, 91, 54, 95, 12, 26, 24, 63,  7, 50,
       34, 85, 67])

In [36]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [39]:
a.min()

7

In [40]:
a.max()

95

In [43]:
sample_array[1:6]

array([1, 2, 3, 4, 5])

In [48]:
rand_array.argmax()

15

# Two-dimensional Array

In [50]:
sample_matrix=np.array(([50,20,1,23],[1,67,83,92],[89,38,28,11]))
sample_matrix

array([[50, 20,  1, 23],
       [ 1, 67, 83, 92],
       [89, 38, 28, 11]])

In [51]:
sample_matrix[1,2]

83

In [52]:
sample_matrix[2,:]

array([89, 38, 28, 11])

In [53]:
sample_matrix[2]

array([89, 38, 28, 11])

In [54]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [92, 83],
       [11, 28]])

# Selection techniques

In [55]:
sample_array=np.arange(1,20)

In [56]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [57]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [58]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [59]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [60]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [61]:
np.max(sample_array
    )

19

In [62]:
np.min(sample_array)

1

In [63]:
np.argmax(sample_array
         )

18

In [64]:
np.argmin(sample_array
         )

0

In [65]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [66]:
np.std(sample_array)

5.477225575051661

In [67]:
np.var(sample_array)

30.0

In [69]:
np.percentile(sample_array,50)

10.0

In [70]:
np.mean(sample_array)

10.0

In [71]:
sports=np.array(['golf','cricket','fball','golf'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')